In [1]:
import torch
from torch.nn import MarginRankingLoss

In [9]:
a = torch.tensor([0, .1, .2, .3])

In [55]:
a.contiguous().view(-1)

tensor([ 0.0000,  0.1000,  0.2000, -0.1000])

In [11]:
a.unsqueeze(-1).expand_as(torch.ones(3, 3))

tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]])

In [13]:
torch.roll(a, 1)

tensor([2, 0, 1])

In [25]:
val = 4


In [29]:
loss = MarginRankingLoss(0)

In [26]:
vmask[2]

tensor([-1., -1., -1., -1.])

In [20]:
vmask = (torch.triu(torch.ones(4, 4))*2-torch.ones(4, 4))*-1

mse = torch.nn.MSELoss()
def rank_loss(preds, golds):
    totloss = 0
    for i in range(1, min(len(preds), 16)):
        # for margin
        margin = (golds - torch.roll(golds, i))*vmask[i]
        diff = (preds - torch.roll(preds, i)-margin)*vmask[i]
        diff[diff<0] = 0
        totloss+=torch.sum(diff)
    return totloss #+ mse(preds, golds)

In [22]:
b = torch.tensor([0.15, .2, .3, .4])

In [11]:
marg = a -torch.roll(a, 1)

In [23]:
rank_loss(b, a)

tensor(0.1500)

In [13]:
vmask[1]

tensor([ 1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        -1., -1., -1., -1.])